name: Cloud-Deployment-Pipeline

on:
  workflow_dispatch:
  push:
    branches: ["main"] # Triggers the workflow on every push to the main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest # Allocates a Virtual Machine (Ubuntu) in the cloud
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Cloud Environment
        uses: actions/configure-pages@v4
        
      - name: Upload Artifact to Cloud Storage
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Uploads the index.html from root
          
      - name: Execute Deployment
        uses: actions/deploy-pages@v4

